global:
  scrape_interval: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nextjs_app'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']
    scrape_interval: 10s
    scrape_timeout: 5s
